### create hotel
POST localhost:8080/hotel/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjg4ODY5MzcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3Mjg5NzMzMzcsImlzcyI6IkhvdGVsIn0.Yaog6RbKeWHM7oqOk0BwRNjcKLlQPYEeIMZa8ozhqLnb5HX3phHILS5ZQ5Ni1Wlh3FYHtwRBRweFH9_B2nqqTg

{
  "name": "Tashkent hotel",
  "address": "Tashkent",
  "description": "There are lux comfort rooms and 5-star rooms"
}

### get by id
GET localhost:8080/hotel/get-byId/1
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjg4ODY5MzcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3Mjg5NzMzMzcsImlzcyI6IkhvdGVsIn0.Yaog6RbKeWHM7oqOk0BwRNjcKLlQPYEeIMZa8ozhqLnb5HX3phHILS5ZQ5Ni1Wlh3FYHtwRBRweFH9_B2nqqTg

### get all hotel
GET localhost:8080/hotel/get-all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjg4ODY5MzcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3Mjg5NzMzMzcsImlzcyI6IkhvdGVsIn0.Yaog6RbKeWHM7oqOk0BwRNjcKLlQPYEeIMZa8ozhqLnb5HX3phHILS5ZQ5Ni1Wlh3FYHtwRBRweFH9_B2nqqTg


