#### create room
POST localhost:8080/room/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjkyNTYxMjgsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MjkzNDI1MjgsImlzcyI6IkhvdGVsIn0.C0GRVc7wOWmwcGDwIzinm6x7dcGF4RHSohmGk8F2nfpPqhlJMNe1dMG5fULRZ3Ok9tJ3uo49gbdTa1XDL5lLCA

{
  "category": "COMFORT",
  "hotelId": 1,
  "number": 1,
  "price": 150.0
}


#### update room
PUT localhost:8080/room/update/13b92aba-cef5-4c21-a35d-08401346ac05
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjg4ODY5MzcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3Mjg5NzMzMzcsImlzcyI6IkhvdGVsIn0.Yaog6RbKeWHM7oqOk0BwRNjcKLlQPYEeIMZa8ozhqLnb5HX3phHILS5ZQ5Ni1Wlh3FYHtwRBRweFH9_B2nqqTg

{
  "category": "LUX",
  "number": 1,
  "price": 200
}

### delete room by id
DELETE localhost:8080/room/delete/13b92aba-cef5-4c21-a35d-08401346ac05
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjg4ODY5MzcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3Mjg5NzMzMzcsImlzcyI6IkhvdGVsIn0.Yaog6RbKeWHM7oqOk0BwRNjcKLlQPYEeIMZa8ozhqLnb5HX3phHILS5ZQ5Ni1Wlh3FYHtwRBRweFH9_B2nqqTg

### get by id
GET localhost:8080/room/get-byId/ae13730a-9a7b-445e-85d0-318c8a7f4e75
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3Mjg4ODY5MzcsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3Mjg5NzMzMzcsImlzcyI6IkhvdGVsIn0.Yaog6RbKeWHM7oqOk0BwRNjcKLlQPYEeIMZa8ozhqLnb5HX3phHILS5ZQ5Ni1Wlh3FYHtwRBRweFH9_B2nqqTg

### get all  pagination  by room number Desc
GET localhost:8080/room/all
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpYXQiOjE3MjkyMzQ3NTAsImVtYWlsIjoiYWRtaW5AZ21haWwuY29tIiwicm9sZSI6IlJPTEVfQURNSU4iLCJleHAiOjE3MjkzMjExNTAsImlzcyI6IkhvdGVsIn0.wIghTTmddOJEwTIdqgAu4OaYMGgpzSuTLQ9h_0UG3Asavu8XGSEW8COYCLgS_P2U7qwC5lUcNqDX8WFKFoQOJA



### filter
POST localhost:8080/room/filter?page=1&size=10
Content-Type: application/json

{
  "status": "EMPTY",
  "hotelId": 1,
  "category": "COMFORT"
}

